# Generated by Django 4.1.5 on 2023-01-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_img_user_file_number_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
