# Generated by Django 4.1.5 on 2023-01-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file_number',
            field=models.CharField(blank=True, max_length=55, null=True, unique=True),
        ),
    ]
