# Generated by Django 4.1.5 on 2023-02-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_file_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=4)),
                ('expertion_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['phone'],
            },
        ),
    ]
